# @package _global_

model:
  type: ??? # Must be specified: standard, mod, sdt, stt
  size: 0.5B
  pretrained_model_name_or_path: "Qwen/Qwen2.5-${model.size}"
  use_cache: True
  tie_word_embeddings: True
  freeze_base_model: False
  prior_ffn_intermediate_size_factor: 0.25

  # Unified block for all model-specific hyperparameters
  params:
    mod_capacity: 0.5
    mod_aux_loss_weight: 0.01

    sdt_capacity: 0.5
    prior_loss_weight: 0.05
    beta_ce_init: -0.3
    beta_cu_init: -0.6
    
    stt_capacity: 0.5
    tpn_loss_weight: 0.05
    causal_loss_weight: 0.10
    
    # Shared params for SDT and STT
    o_ce_init: 1.025
    m_cu_init: 1.1
    ma_window: 100

  # STT-specific schedule
  beta_schedule:
    type: "cosine"
    beta_ce_start: 0.3
    beta_ce_end: 6.0
    beta_cu_start: 0.3
    beta_cu_end: 6.0
    warmup_steps: 1000

  # Scratch config remains the same
  scratch_config:
    # ...
