# config/model/sdt.yaml

defaults:
  - /component/prior
  - /component/causal_router

type: sdt
size: 0.5B

# SDT-specific parameters
sdt_capacity: 0.5
ma_window: 100
o_ce_init: 1.025
m_cu_init: 1.1
beta_ce_init: -0.3
beta_cu_init: -0.6

# SDT uses a beta schedule
beta_schedule:
  type: "cosine"
  beta_ce_start: 0.3
  beta_ce_end: 6.0
  beta_cu_start: 0.3
  beta_cu_end: 6.0
  warmup_steps: 1000