# pyproject.toml
[project]
name = "dynamic-transformer"
version = "0.1.0"
description = "Dynamic Transformer"
authors = [
  { name="Fred", email="fred@example.com" },
]
readme = "README.md"
license = { file="LICENSE" } # It's good practice to add a LICENSE file (e.g., MIT, Apache-2.0)
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

# --- Core Dependencies ---
# These are the essential packages required to run the main training script.
dependencies = [
    "torch>=2.2.0",
    "pytorch-lightning>=2.2.0",
    "hydra-core>=1.3.2",
    # Omegaconf and its dependencies are pinned to versions known to be stable together.
    "omegaconf>=2.3.0",
    "antlr4-python3-runtime", # '~=4.10.1' means '>=4.10.1, <4.11.0'
    "PyYAML>=6.0",
    # Hugging Face ecosystem
    "transformers==4.42.4",
    "datasets>=2.18.0",
    "accelerate>=0.27.0",
    "safetensors>=0.4.2",
    "sentencepiece>=0.2.0", # Often a required tokenizer dependency
    "tensorboard>=2.19.0",
]

[project.urls]
"Homepage" = "https://github.com/user/repo" # Replace with your repo URL
"Bug Tracker" = "https://github.com/user/repo/issues" # Replace with your repo URL

[project.optional-dependencies]
# --- Logging Dependencies ---
# Install with: uv pip install -e ".[logging]"
logging = [
    "wandb>=0.16.0",
    "tensorboard>=2.16.0",
]

# --- Development Dependencies ---
# Install with: uv pip install -e ".[dev]"
dev = [
    "pytest>=8.0",
    "ipykernel", # For Jupyter notebook support
    "ruff",      # For linting and formatting
]

# To install all optional dependencies, use:
# uv pip install -e ".[logging,dev]" or uv pip sync --all-extras

[tool.ruff]
# See https://docs.astral.sh/ruff/configuration/
line-length = 88
indent-width = 4

[tool.ruff.lint]
# A good starting set of rules
select = ["E", "F", "W", "I", "UP", "B", "C4"]
ignore = []

[tool.ruff.format]
quote-style = "double"
