# pyproject.toml
[project]
name = "dvd-transformer"
version = "0.1.0"
description = "Dynamic Variational Decoder Transformer"
requires-python = ">=3.10"

# Dependencies should be a list of strings
dependencies = [
    "transformers",
    "torch",
    "datasets",
    "wandb",
    "tensorboard",
    "accelerate",
    "scipy",
    "numpy",
    "tqdm",
    "typing_extensions",
]

