# config/system/gpu.yaml
system:
  device: "cuda"
  precision: "bf16"
  use_flash_attention: true
  compile_model: false
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  torch_dtype: "bfloat16"