defaults:
  - _self_
  - data: mixed_training
  - model: small_50m

# Model selection
model_type: "dtf"  # DTF performs better than MoD

# Training configuration optimized for Mac
training:
  # Duration
  num_epochs: 3
  max_steps: 10000  # Limit for testing

  # Batch settings for Mac memory constraints
  gradient_accumulation_steps: 16  # Effective batch = 8 * 16 = 128
  gradient_clip_val: 1.0

  # Optimizer settings
  optimizer:
    lr: 3e-4  # Higher LR for small model
    weight_decay: 0.1
    warmup_ratio: 0.05
    scheduler: "cosine_with_restarts"
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_epsilon: 1e-8

  # Learning rate multipliers
  lr_multipliers:
    base_model: 1.0
    router: 5.0     # Less aggressive than default
    prior: 5.0

  # Evaluation
  eval_interval: 500
  save_interval: 1000
  eval_samples: 1000  # Limit validation samples for speed

  # Memory optimization
  gradient_checkpointing: true
  mixed_precision: false  # Disable for Mac stability

# Logging
logging:
  wandb:
    enabled: true
    project: "dynamic-transformer-mac"
    entity: null
    tags: ["mac", "50m", "dtf"]

  log_interval: 50
  log_grad_norm: true

# System settings for Mac
system:
  seed: 42
  output_dir: "outputs/mac_${model_type}_${now:%Y%m%d_%H%M%S}"

  # Mac-specific settings
  device: "mps"  # Use Metal Performance Shaders if available
  num_workers: 4  # Reasonable for Mac
  pin_memory: false  # Not supported on Mac

  # Compilation (experimental on Mac)
  compile: false
  compile_mode: null

# Data loader settings for Mac
dataloader:
  persistent_workers: false  # Better for Mac
  prefetch_factor: 2
  drop_last: true

# Checkpointing
checkpoint:
  save_total_limit: 3
  save_best: true
  metric: "val_loss"
  mode: "min"

# Early stopping
early_stopping:
  enabled: true
  patience: 5
  min_delta: 0.001

# Hydra configuration
hydra:
  run:
    dir: ${system.output_dir}
  sweep:
    dir: outputs/sweeps/${now:%Y%m%d_%H%M%S}
  job:
    chdir: false