# Standard Transformer - Transfer Learning
defaults:
  - train
  - _self_

model:
  type: standard
  size: 0.5B

training:
  from_scratch: false  # Load Qwen2.5 weights
  optimizer:
    lr: 1e-4  # Lower LR for fine-tuning
  num_epochs: 5